services:
  market-data-test:
    build:
      context: .
      args:
        GITHUB_ACTOR:
        GITHUB_TOKEN:
    container_name: gnomepy-testing
    environment:
      - LISTING_ID=8
      - DURATION=10
      - OUTPUT_DIR=/app/output
      - PROXY_PORT=8765
      - STAGE=dev
      - REGISTRY_API_KEY_ID=rb0pbivke8
      - AWS_PROFILE=dev
    volumes:
      - ./output:/app/output
      - ~/.aws/:/root/.aws
